//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ModelsEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Algoritmos_Cifrado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Algoritmos_Cifrado()
        {
            this.Nivel_Privacidad = new HashSet<Nivel_Privacidad>();
        }
    
        public int Id_Algoritmo { get; set; }
        public string Algoritmo { get; set; }
        public string KeyUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nivel_Privacidad> Nivel_Privacidad { get; set; }
    }
}
