//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ModelsEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SaatyEntities : DbContext
    {
        public SaatyEntities()
            : base("name=SaatyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Algoritmos_Cifrado> Algoritmos_Cifrado { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<Documentos_Usuarios> Documentos_Usuarios { get; set; }
        public virtual DbSet<Nivel_Privacidad> Nivel_Privacidad { get; set; }
        public virtual DbSet<Segmentacion> Segmentacion { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
    
        public virtual int crud___MigrationHistoryDelete(string contextKey)
        {
            var contextKeyParameter = contextKey != null ?
                new ObjectParameter("ContextKey", contextKey) :
                new ObjectParameter("ContextKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud___MigrationHistoryDelete", contextKeyParameter);
        }
    
        public virtual ObjectResult<crud___MigrationHistoryInsert_Result> crud___MigrationHistoryInsert(byte[] model, string productVersion)
        {
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(byte[]));
    
            var productVersionParameter = productVersion != null ?
                new ObjectParameter("ProductVersion", productVersion) :
                new ObjectParameter("ProductVersion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud___MigrationHistoryInsert_Result>("crud___MigrationHistoryInsert", modelParameter, productVersionParameter);
        }
    
        public virtual ObjectResult<crud___MigrationHistorySelect_Result> crud___MigrationHistorySelect(string contextKey)
        {
            var contextKeyParameter = contextKey != null ?
                new ObjectParameter("ContextKey", contextKey) :
                new ObjectParameter("ContextKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud___MigrationHistorySelect_Result>("crud___MigrationHistorySelect", contextKeyParameter);
        }
    
        public virtual int crud___MigrationHistoryUpdate(string contextKey, byte[] model, string productVersion)
        {
            var contextKeyParameter = contextKey != null ?
                new ObjectParameter("ContextKey", contextKey) :
                new ObjectParameter("ContextKey", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(byte[]));
    
            var productVersionParameter = productVersion != null ?
                new ObjectParameter("ProductVersion", productVersion) :
                new ObjectParameter("ProductVersion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud___MigrationHistoryUpdate", contextKeyParameter, modelParameter, productVersionParameter);
        }
    
        public virtual int crud_Algoritmos_CifradoDelete(Nullable<int> id_Algoritmo)
        {
            var id_AlgoritmoParameter = id_Algoritmo.HasValue ?
                new ObjectParameter("Id_Algoritmo", id_Algoritmo) :
                new ObjectParameter("Id_Algoritmo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_Algoritmos_CifradoDelete", id_AlgoritmoParameter);
        }
    
        public virtual ObjectResult<crud_Algoritmos_CifradoInsert_Result> crud_Algoritmos_CifradoInsert(string algoritmo, string keyUrl)
        {
            var algoritmoParameter = algoritmo != null ?
                new ObjectParameter("Algoritmo", algoritmo) :
                new ObjectParameter("Algoritmo", typeof(string));
    
            var keyUrlParameter = keyUrl != null ?
                new ObjectParameter("KeyUrl", keyUrl) :
                new ObjectParameter("KeyUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_Algoritmos_CifradoInsert_Result>("crud_Algoritmos_CifradoInsert", algoritmoParameter, keyUrlParameter);
        }
    
        public virtual ObjectResult<crud_Algoritmos_CifradoSelect_Result> crud_Algoritmos_CifradoSelect(Nullable<int> id_Algoritmo)
        {
            var id_AlgoritmoParameter = id_Algoritmo.HasValue ?
                new ObjectParameter("Id_Algoritmo", id_Algoritmo) :
                new ObjectParameter("Id_Algoritmo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_Algoritmos_CifradoSelect_Result>("crud_Algoritmos_CifradoSelect", id_AlgoritmoParameter);
        }
    
        public virtual int crud_Algoritmos_CifradoUpdate(Nullable<int> id_Algoritmo, string algoritmo, string keyUrl)
        {
            var id_AlgoritmoParameter = id_Algoritmo.HasValue ?
                new ObjectParameter("Id_Algoritmo", id_Algoritmo) :
                new ObjectParameter("Id_Algoritmo", typeof(int));
    
            var algoritmoParameter = algoritmo != null ?
                new ObjectParameter("Algoritmo", algoritmo) :
                new ObjectParameter("Algoritmo", typeof(string));
    
            var keyUrlParameter = keyUrl != null ?
                new ObjectParameter("KeyUrl", keyUrl) :
                new ObjectParameter("KeyUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_Algoritmos_CifradoUpdate", id_AlgoritmoParameter, algoritmoParameter, keyUrlParameter);
        }
    
        public virtual int crud_AspNetRolesDelete(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetRolesDelete", idParameter);
        }
    
        public virtual ObjectResult<crud_AspNetRolesInsert_Result> crud_AspNetRolesInsert(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_AspNetRolesInsert_Result>("crud_AspNetRolesInsert", nameParameter);
        }
    
        public virtual ObjectResult<crud_AspNetRolesSelect_Result> crud_AspNetRolesSelect(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_AspNetRolesSelect_Result>("crud_AspNetRolesSelect", idParameter);
        }
    
        public virtual int crud_AspNetRolesUpdate(string id, string name)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetRolesUpdate", idParameter, nameParameter);
        }
    
        public virtual int crud_AspNetUserClaimsDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetUserClaimsDelete", idParameter);
        }
    
        public virtual ObjectResult<crud_AspNetUserClaimsInsert_Result> crud_AspNetUserClaimsInsert(string userId, string claimType, string claimValue)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var claimTypeParameter = claimType != null ?
                new ObjectParameter("ClaimType", claimType) :
                new ObjectParameter("ClaimType", typeof(string));
    
            var claimValueParameter = claimValue != null ?
                new ObjectParameter("ClaimValue", claimValue) :
                new ObjectParameter("ClaimValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_AspNetUserClaimsInsert_Result>("crud_AspNetUserClaimsInsert", userIdParameter, claimTypeParameter, claimValueParameter);
        }
    
        public virtual ObjectResult<crud_AspNetUserClaimsSelect_Result> crud_AspNetUserClaimsSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_AspNetUserClaimsSelect_Result>("crud_AspNetUserClaimsSelect", idParameter);
        }
    
        public virtual int crud_AspNetUserClaimsUpdate(Nullable<int> id, string userId, string claimType, string claimValue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var claimTypeParameter = claimType != null ?
                new ObjectParameter("ClaimType", claimType) :
                new ObjectParameter("ClaimType", typeof(string));
    
            var claimValueParameter = claimValue != null ?
                new ObjectParameter("ClaimValue", claimValue) :
                new ObjectParameter("ClaimValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetUserClaimsUpdate", idParameter, userIdParameter, claimTypeParameter, claimValueParameter);
        }
    
        public virtual int crud_AspNetUserLoginsDelete(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetUserLoginsDelete", userIdParameter);
        }
    
        public virtual ObjectResult<string> crud_AspNetUserLoginsSelect(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("crud_AspNetUserLoginsSelect", userIdParameter);
        }
    
        public virtual int crud_AspNetUserRolesDelete(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetUserRolesDelete", roleIdParameter);
        }
    
        public virtual ObjectResult<string> crud_AspNetUserRolesSelect(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("crud_AspNetUserRolesSelect", roleIdParameter);
        }
    
        public virtual int crud_AspNetUsersDelete(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetUsersDelete", idParameter);
        }
    
        public virtual ObjectResult<crud_AspNetUsersInsert_Result> crud_AspNetUsersInsert(string email, Nullable<bool> emailConfirmed, string passwordHash, string securityStamp, string phoneNumber, Nullable<bool> phoneNumberConfirmed, Nullable<bool> twoFactorEnabled, Nullable<System.DateTime> lockoutEndDateUtc, Nullable<bool> lockoutEnabled, Nullable<int> accessFailedCount, string userName, string discriminator, string nombre, string apellido)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var emailConfirmedParameter = emailConfirmed.HasValue ?
                new ObjectParameter("EmailConfirmed", emailConfirmed) :
                new ObjectParameter("EmailConfirmed", typeof(bool));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var securityStampParameter = securityStamp != null ?
                new ObjectParameter("SecurityStamp", securityStamp) :
                new ObjectParameter("SecurityStamp", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var phoneNumberConfirmedParameter = phoneNumberConfirmed.HasValue ?
                new ObjectParameter("PhoneNumberConfirmed", phoneNumberConfirmed) :
                new ObjectParameter("PhoneNumberConfirmed", typeof(bool));
    
            var twoFactorEnabledParameter = twoFactorEnabled.HasValue ?
                new ObjectParameter("TwoFactorEnabled", twoFactorEnabled) :
                new ObjectParameter("TwoFactorEnabled", typeof(bool));
    
            var lockoutEndDateUtcParameter = lockoutEndDateUtc.HasValue ?
                new ObjectParameter("LockoutEndDateUtc", lockoutEndDateUtc) :
                new ObjectParameter("LockoutEndDateUtc", typeof(System.DateTime));
    
            var lockoutEnabledParameter = lockoutEnabled.HasValue ?
                new ObjectParameter("LockoutEnabled", lockoutEnabled) :
                new ObjectParameter("LockoutEnabled", typeof(bool));
    
            var accessFailedCountParameter = accessFailedCount.HasValue ?
                new ObjectParameter("AccessFailedCount", accessFailedCount) :
                new ObjectParameter("AccessFailedCount", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var discriminatorParameter = discriminator != null ?
                new ObjectParameter("Discriminator", discriminator) :
                new ObjectParameter("Discriminator", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_AspNetUsersInsert_Result>("crud_AspNetUsersInsert", emailParameter, emailConfirmedParameter, passwordHashParameter, securityStampParameter, phoneNumberParameter, phoneNumberConfirmedParameter, twoFactorEnabledParameter, lockoutEndDateUtcParameter, lockoutEnabledParameter, accessFailedCountParameter, userNameParameter, discriminatorParameter, nombreParameter, apellidoParameter);
        }
    
        public virtual ObjectResult<crud_AspNetUsersSelect_Result> crud_AspNetUsersSelect(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_AspNetUsersSelect_Result>("crud_AspNetUsersSelect", idParameter);
        }
    
        public virtual int crud_AspNetUsersUpdate(string id, string email, Nullable<bool> emailConfirmed, string passwordHash, string securityStamp, string phoneNumber, Nullable<bool> phoneNumberConfirmed, Nullable<bool> twoFactorEnabled, Nullable<System.DateTime> lockoutEndDateUtc, Nullable<bool> lockoutEnabled, Nullable<int> accessFailedCount, string userName, string discriminator, string nombre, string apellido)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var emailConfirmedParameter = emailConfirmed.HasValue ?
                new ObjectParameter("EmailConfirmed", emailConfirmed) :
                new ObjectParameter("EmailConfirmed", typeof(bool));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var securityStampParameter = securityStamp != null ?
                new ObjectParameter("SecurityStamp", securityStamp) :
                new ObjectParameter("SecurityStamp", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var phoneNumberConfirmedParameter = phoneNumberConfirmed.HasValue ?
                new ObjectParameter("PhoneNumberConfirmed", phoneNumberConfirmed) :
                new ObjectParameter("PhoneNumberConfirmed", typeof(bool));
    
            var twoFactorEnabledParameter = twoFactorEnabled.HasValue ?
                new ObjectParameter("TwoFactorEnabled", twoFactorEnabled) :
                new ObjectParameter("TwoFactorEnabled", typeof(bool));
    
            var lockoutEndDateUtcParameter = lockoutEndDateUtc.HasValue ?
                new ObjectParameter("LockoutEndDateUtc", lockoutEndDateUtc) :
                new ObjectParameter("LockoutEndDateUtc", typeof(System.DateTime));
    
            var lockoutEnabledParameter = lockoutEnabled.HasValue ?
                new ObjectParameter("LockoutEnabled", lockoutEnabled) :
                new ObjectParameter("LockoutEnabled", typeof(bool));
    
            var accessFailedCountParameter = accessFailedCount.HasValue ?
                new ObjectParameter("AccessFailedCount", accessFailedCount) :
                new ObjectParameter("AccessFailedCount", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var discriminatorParameter = discriminator != null ?
                new ObjectParameter("Discriminator", discriminator) :
                new ObjectParameter("Discriminator", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_AspNetUsersUpdate", idParameter, emailParameter, emailConfirmedParameter, passwordHashParameter, securityStampParameter, phoneNumberParameter, phoneNumberConfirmedParameter, twoFactorEnabledParameter, lockoutEndDateUtcParameter, lockoutEnabledParameter, accessFailedCountParameter, userNameParameter, discriminatorParameter, nombreParameter, apellidoParameter);
        }
    
        public virtual int crud_Documentos_UsuariosDelete(Nullable<int> id_Permisos)
        {
            var id_PermisosParameter = id_Permisos.HasValue ?
                new ObjectParameter("Id_Permisos", id_Permisos) :
                new ObjectParameter("Id_Permisos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_Documentos_UsuariosDelete", id_PermisosParameter);
        }
    
        public virtual ObjectResult<crud_Documentos_UsuariosInsert_Result> crud_Documentos_UsuariosInsert(Nullable<int> id_Documento, string id_user)
        {
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            var id_userParameter = id_user != null ?
                new ObjectParameter("Id_user", id_user) :
                new ObjectParameter("Id_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_Documentos_UsuariosInsert_Result>("crud_Documentos_UsuariosInsert", id_DocumentoParameter, id_userParameter);
        }
    
        public virtual ObjectResult<crud_Documentos_UsuariosSelect_Result> crud_Documentos_UsuariosSelect(Nullable<int> id_Permisos)
        {
            var id_PermisosParameter = id_Permisos.HasValue ?
                new ObjectParameter("Id_Permisos", id_Permisos) :
                new ObjectParameter("Id_Permisos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_Documentos_UsuariosSelect_Result>("crud_Documentos_UsuariosSelect", id_PermisosParameter);
        }
    
        public virtual int crud_Documentos_UsuariosUpdate(Nullable<int> id_Permisos, Nullable<int> id_Documento, string id_user)
        {
            var id_PermisosParameter = id_Permisos.HasValue ?
                new ObjectParameter("Id_Permisos", id_Permisos) :
                new ObjectParameter("Id_Permisos", typeof(int));
    
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            var id_userParameter = id_user != null ?
                new ObjectParameter("Id_user", id_user) :
                new ObjectParameter("Id_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_Documentos_UsuariosUpdate", id_PermisosParameter, id_DocumentoParameter, id_userParameter);
        }
    
        public virtual int crud_DocumentosDelete(Nullable<int> id_Documento)
        {
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_DocumentosDelete", id_DocumentoParameter);
        }
    
        public virtual ObjectResult<crud_DocumentosInsert_Result> crud_DocumentosInsert(Nullable<int> id_NivelPrivacidad, string nombre, Nullable<int> numero_Segmentos, string hashDocumento)
        {
            var id_NivelPrivacidadParameter = id_NivelPrivacidad.HasValue ?
                new ObjectParameter("Id_NivelPrivacidad", id_NivelPrivacidad) :
                new ObjectParameter("Id_NivelPrivacidad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var numero_SegmentosParameter = numero_Segmentos.HasValue ?
                new ObjectParameter("Numero_Segmentos", numero_Segmentos) :
                new ObjectParameter("Numero_Segmentos", typeof(int));
    
            var hashDocumentoParameter = hashDocumento != null ?
                new ObjectParameter("HashDocumento", hashDocumento) :
                new ObjectParameter("HashDocumento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_DocumentosInsert_Result>("crud_DocumentosInsert", id_NivelPrivacidadParameter, nombreParameter, numero_SegmentosParameter, hashDocumentoParameter);
        }
    
        public virtual ObjectResult<crud_DocumentosSelect_Result> crud_DocumentosSelect(Nullable<int> id_Documento)
        {
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_DocumentosSelect_Result>("crud_DocumentosSelect", id_DocumentoParameter);
        }
    
        public virtual int crud_DocumentosUpdate(Nullable<int> id_Documento, Nullable<int> id_NivelPrivacidad, string nombre, Nullable<int> numero_Segmentos, string hashDocumento)
        {
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            var id_NivelPrivacidadParameter = id_NivelPrivacidad.HasValue ?
                new ObjectParameter("Id_NivelPrivacidad", id_NivelPrivacidad) :
                new ObjectParameter("Id_NivelPrivacidad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var numero_SegmentosParameter = numero_Segmentos.HasValue ?
                new ObjectParameter("Numero_Segmentos", numero_Segmentos) :
                new ObjectParameter("Numero_Segmentos", typeof(int));
    
            var hashDocumentoParameter = hashDocumento != null ?
                new ObjectParameter("HashDocumento", hashDocumento) :
                new ObjectParameter("HashDocumento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_DocumentosUpdate", id_DocumentoParameter, id_NivelPrivacidadParameter, nombreParameter, numero_SegmentosParameter, hashDocumentoParameter);
        }
    
        public virtual int crud_Nivel_PrivacidadDelete(Nullable<int> id_NivelPrivacidad)
        {
            var id_NivelPrivacidadParameter = id_NivelPrivacidad.HasValue ?
                new ObjectParameter("Id_NivelPrivacidad", id_NivelPrivacidad) :
                new ObjectParameter("Id_NivelPrivacidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_Nivel_PrivacidadDelete", id_NivelPrivacidadParameter);
        }
    
        public virtual ObjectResult<crud_Nivel_PrivacidadInsert_Result> crud_Nivel_PrivacidadInsert(Nullable<int> id_Algoritmo, string nivelPrivacidad, string descripcionPrivacidad)
        {
            var id_AlgoritmoParameter = id_Algoritmo.HasValue ?
                new ObjectParameter("Id_Algoritmo", id_Algoritmo) :
                new ObjectParameter("Id_Algoritmo", typeof(int));
    
            var nivelPrivacidadParameter = nivelPrivacidad != null ?
                new ObjectParameter("NivelPrivacidad", nivelPrivacidad) :
                new ObjectParameter("NivelPrivacidad", typeof(string));
    
            var descripcionPrivacidadParameter = descripcionPrivacidad != null ?
                new ObjectParameter("DescripcionPrivacidad", descripcionPrivacidad) :
                new ObjectParameter("DescripcionPrivacidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_Nivel_PrivacidadInsert_Result>("crud_Nivel_PrivacidadInsert", id_AlgoritmoParameter, nivelPrivacidadParameter, descripcionPrivacidadParameter);
        }
    
        public virtual ObjectResult<crud_Nivel_PrivacidadSelect_Result> crud_Nivel_PrivacidadSelect(Nullable<int> id_NivelPrivacidad)
        {
            var id_NivelPrivacidadParameter = id_NivelPrivacidad.HasValue ?
                new ObjectParameter("Id_NivelPrivacidad", id_NivelPrivacidad) :
                new ObjectParameter("Id_NivelPrivacidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_Nivel_PrivacidadSelect_Result>("crud_Nivel_PrivacidadSelect", id_NivelPrivacidadParameter);
        }
    
        public virtual int crud_Nivel_PrivacidadUpdate(Nullable<int> id_NivelPrivacidad, Nullable<int> id_Algoritmo, string nivelPrivacidad, string descripcionPrivacidad)
        {
            var id_NivelPrivacidadParameter = id_NivelPrivacidad.HasValue ?
                new ObjectParameter("Id_NivelPrivacidad", id_NivelPrivacidad) :
                new ObjectParameter("Id_NivelPrivacidad", typeof(int));
    
            var id_AlgoritmoParameter = id_Algoritmo.HasValue ?
                new ObjectParameter("Id_Algoritmo", id_Algoritmo) :
                new ObjectParameter("Id_Algoritmo", typeof(int));
    
            var nivelPrivacidadParameter = nivelPrivacidad != null ?
                new ObjectParameter("NivelPrivacidad", nivelPrivacidad) :
                new ObjectParameter("NivelPrivacidad", typeof(string));
    
            var descripcionPrivacidadParameter = descripcionPrivacidad != null ?
                new ObjectParameter("DescripcionPrivacidad", descripcionPrivacidad) :
                new ObjectParameter("DescripcionPrivacidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_Nivel_PrivacidadUpdate", id_NivelPrivacidadParameter, id_AlgoritmoParameter, nivelPrivacidadParameter, descripcionPrivacidadParameter);
        }
    
        public virtual int crud_SegmentacionDelete(Nullable<int> id_Segmentacion)
        {
            var id_SegmentacionParameter = id_Segmentacion.HasValue ?
                new ObjectParameter("Id_Segmentacion", id_Segmentacion) :
                new ObjectParameter("Id_Segmentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_SegmentacionDelete", id_SegmentacionParameter);
        }
    
        public virtual ObjectResult<crud_SegmentacionInsert_Result> crud_SegmentacionInsert(Nullable<int> id_Storage, Nullable<int> id_Documento, Nullable<int> posicion, string urlSegmento, string hashSegmento, string hashAnt, string hashPos)
        {
            var id_StorageParameter = id_Storage.HasValue ?
                new ObjectParameter("Id_Storage", id_Storage) :
                new ObjectParameter("Id_Storage", typeof(int));
    
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            var posicionParameter = posicion.HasValue ?
                new ObjectParameter("Posicion", posicion) :
                new ObjectParameter("Posicion", typeof(int));
    
            var urlSegmentoParameter = urlSegmento != null ?
                new ObjectParameter("UrlSegmento", urlSegmento) :
                new ObjectParameter("UrlSegmento", typeof(string));
    
            var hashSegmentoParameter = hashSegmento != null ?
                new ObjectParameter("HashSegmento", hashSegmento) :
                new ObjectParameter("HashSegmento", typeof(string));
    
            var hashAntParameter = hashAnt != null ?
                new ObjectParameter("HashAnt", hashAnt) :
                new ObjectParameter("HashAnt", typeof(string));
    
            var hashPosParameter = hashPos != null ?
                new ObjectParameter("HashPos", hashPos) :
                new ObjectParameter("HashPos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_SegmentacionInsert_Result>("crud_SegmentacionInsert", id_StorageParameter, id_DocumentoParameter, posicionParameter, urlSegmentoParameter, hashSegmentoParameter, hashAntParameter, hashPosParameter);
        }
    
        public virtual ObjectResult<crud_SegmentacionSelect_Result> crud_SegmentacionSelect(Nullable<int> id_Segmentacion)
        {
            var id_SegmentacionParameter = id_Segmentacion.HasValue ?
                new ObjectParameter("Id_Segmentacion", id_Segmentacion) :
                new ObjectParameter("Id_Segmentacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_SegmentacionSelect_Result>("crud_SegmentacionSelect", id_SegmentacionParameter);
        }
    
        public virtual int crud_SegmentacionUpdate(Nullable<int> id_Segmentacion, Nullable<int> id_Storage, Nullable<int> id_Documento, Nullable<int> posicion, string urlSegmento, string hashSegmento, string hashAnt, string hashPos)
        {
            var id_SegmentacionParameter = id_Segmentacion.HasValue ?
                new ObjectParameter("Id_Segmentacion", id_Segmentacion) :
                new ObjectParameter("Id_Segmentacion", typeof(int));
    
            var id_StorageParameter = id_Storage.HasValue ?
                new ObjectParameter("Id_Storage", id_Storage) :
                new ObjectParameter("Id_Storage", typeof(int));
    
            var id_DocumentoParameter = id_Documento.HasValue ?
                new ObjectParameter("Id_Documento", id_Documento) :
                new ObjectParameter("Id_Documento", typeof(int));
    
            var posicionParameter = posicion.HasValue ?
                new ObjectParameter("Posicion", posicion) :
                new ObjectParameter("Posicion", typeof(int));
    
            var urlSegmentoParameter = urlSegmento != null ?
                new ObjectParameter("UrlSegmento", urlSegmento) :
                new ObjectParameter("UrlSegmento", typeof(string));
    
            var hashSegmentoParameter = hashSegmento != null ?
                new ObjectParameter("HashSegmento", hashSegmento) :
                new ObjectParameter("HashSegmento", typeof(string));
    
            var hashAntParameter = hashAnt != null ?
                new ObjectParameter("HashAnt", hashAnt) :
                new ObjectParameter("HashAnt", typeof(string));
    
            var hashPosParameter = hashPos != null ?
                new ObjectParameter("HashPos", hashPos) :
                new ObjectParameter("HashPos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_SegmentacionUpdate", id_SegmentacionParameter, id_StorageParameter, id_DocumentoParameter, posicionParameter, urlSegmentoParameter, hashSegmentoParameter, hashAntParameter, hashPosParameter);
        }
    
        public virtual int crud_StorageDelete(Nullable<int> id_Storage)
        {
            var id_StorageParameter = id_Storage.HasValue ?
                new ObjectParameter("Id_Storage", id_Storage) :
                new ObjectParameter("Id_Storage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_StorageDelete", id_StorageParameter);
        }
    
        public virtual ObjectResult<crud_StorageInsert_Result> crud_StorageInsert(string nombreStorage, string urlStorage)
        {
            var nombreStorageParameter = nombreStorage != null ?
                new ObjectParameter("NombreStorage", nombreStorage) :
                new ObjectParameter("NombreStorage", typeof(string));
    
            var urlStorageParameter = urlStorage != null ?
                new ObjectParameter("UrlStorage", urlStorage) :
                new ObjectParameter("UrlStorage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_StorageInsert_Result>("crud_StorageInsert", nombreStorageParameter, urlStorageParameter);
        }
    
        public virtual ObjectResult<crud_StorageSelect_Result> crud_StorageSelect(Nullable<int> id_Storage)
        {
            var id_StorageParameter = id_Storage.HasValue ?
                new ObjectParameter("Id_Storage", id_Storage) :
                new ObjectParameter("Id_Storage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<crud_StorageSelect_Result>("crud_StorageSelect", id_StorageParameter);
        }
    
        public virtual int crud_StorageUpdate(Nullable<int> id_Storage, string nombreStorage, string urlStorage)
        {
            var id_StorageParameter = id_Storage.HasValue ?
                new ObjectParameter("Id_Storage", id_Storage) :
                new ObjectParameter("Id_Storage", typeof(int));
    
            var nombreStorageParameter = nombreStorage != null ?
                new ObjectParameter("NombreStorage", nombreStorage) :
                new ObjectParameter("NombreStorage", typeof(string));
    
            var urlStorageParameter = urlStorage != null ?
                new ObjectParameter("UrlStorage", urlStorage) :
                new ObjectParameter("UrlStorage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crud_StorageUpdate", id_StorageParameter, nombreStorageParameter, urlStorageParameter);
        }
    }
}
