//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ModelsEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos_Usuarios
    {
        public int Id_Permisos { get; set; }
        public int Id_Documento { get; set; }
        public string Id_user { get; set; }
    
        public virtual Documentos Documentos { get; set; }
    }
}
