//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ModelsEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentos()
        {
            this.Documentos_Usuarios = new HashSet<Documentos_Usuarios>();
            this.Segmentacion = new HashSet<Segmentacion>();
        }
    
        public int Id_Documento { get; set; }
        public int Id_NivelPrivacidad { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Numero_Segmentos { get; set; }
        public string HashDocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos_Usuarios> Documentos_Usuarios { get; set; }
        public virtual Nivel_Privacidad Nivel_Privacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Segmentacion> Segmentacion { get; set; }
    }
}
